---
title: "Taller en clase: Regresión Múltiple"
author: "Felipe Clement - Lina Quintero"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, include=FALSE}
library(AER)
library(data.table)
library(dplyr)
library(formattable)
library(tidyr)


data <- read.csv("data.csv")[, -c(1:2)]
```

```{r model_gen}
generate_model <- function(data_frame, indep_variable, dep_variable_range) {
  attach(data_frame)
  column_names <- colnames(data_frame[, dep_variable_range])
  model_formula <- paste(indep_variable, " ~ ", paste(column_names, collapse = " + "))
  model <- lm(model_formula, data)
  detach(data_frame)

  return(model)
}
```

```{r models}
model_all <- generate_model(data, "shares", 1:29)
model_1 <- generate_model(data, "shares", 1:12)
model_2 <- generate_model(data, "shares", 13:29)
```

```{r individual}
r_squared_adj <- c(
  summary(model_all)$adj.r.squared,
  summary(model_1)$adj.r.squared,
  summary(model_2)$adj.r.squared
)

aic <- c(
  AIC(model_all),
  AIC(model_1),
  AIC(model_2)
)

bic <- c(
  BIC(model_all),
  BIC(model_1),
  BIC(model_2)
)
```

```{r visualize}
customGreen0 <- "#DeF7E9"
customGreen <- "#71CA97"

row_names <- c("Model All", "Model 1", "Model 2")
consolidated <- data.frame(r_squared_adj, aic, bic, row.names = row_names)
formattable(consolidated,
  align = c("l", rep("c", 3)),
  list(
    r_squared_adj = color_tile(customGreen, customGreen0),
    aic = color_tile(customGreen, customGreen0),
    bic = color_tile(customGreen, customGreen0)
  )
)
```

```{r m1_v_all}
anova(model_1, model_all)
anova(model_2, model_all)
```

Podemos decir que los dos modelos con menos variables son mejores que el que tiene todas, procedemos a analizar cuales de los dos anidados es mejor.

```{r j}
j_test <- jtest(model_1, model_2)
j_test
```
